# Generated by Django 2.0.13 on 2019-06-06 09:01

from django.db import migrations, models
import informant.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('informant', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='transport',
            field=models.CharField(choices=[(informant.helpers.TransportChoice('Autobus'), 'Autobus'), (informant.helpers.TransportChoice('Tramwaj'), 'Tramwaj'), (informant.helpers.TransportChoice('Oba'), 'Oba')], default='BOTH', max_length=5),
            preserve_default=False,
        ),
    ]
